// 90 New Verified Padel Clubs (IDs 52-141)
// Extracted from NEW_FACILITIES_VERIFIED.md - Verification Date: 2025-10-13

const newClubs = [
  {
    id: 52,
    name: "Pulse Padel Hub",
    address: "1355 Northwest 135th Street",
    city: "North Miami",
    state: "FL",
    zipCode: "33167",
    phone: "+17863818163",
    website: "https://pulsepadelhub.com",
    rating: 5.0,
    reviewCount: 5,
    numberOfCourts: 6,
    courtType: "outdoor" as const,
    amenities: ["Free Parking", "Coaching", "Community Events"],
    openingHours: {
      monday: "9h-21h",
      tuesday: "9h-21h",
      wednesday: "9h-21h",
      thursday: "9h-21h",
      friday: "9h-21h",
      saturday: "9h-21h",
      sunday: "9h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 53,
    name: "Padel X Miami",
    address: "141 NE 13th Terrace",
    city: "Miami",
    state: "FL",
    zipCode: "33132",
    phone: "+13055150956",
    website: "https://padelx.us",
    rating: 4.5,
    reviewCount: 15,
    courtType: "outdoor" as const,
    amenities: ["Professional Coaching", "Artificial Grass Courts", "Technology Enhanced"],
    openingHours: {
      monday: "9h-22h",
      tuesday: "9h-22h",
      wednesday: "9h-22h",
      thursday: "9h-22h",
      friday: "9h-22h",
      saturday: "9h-22h",
      sunday: "9h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 54,
    name: "Padel MKE",
    address: "737 W Cleveland Ave",
    city: "Milwaukee",
    state: "WI",
    zipCode: "85215",
    phone: "+14142311272",
    website: "https://www.padelmke.com",
    rating: 5.0,
    reviewCount: 10,
    courtType: "indoor" as const,
    amenities: ["Classes", "Social Mixers", "Birthday Parties", "Free First Hour for New Players"],
    openingHours: {
      monday: "9h-22h",
      tuesday: "9h-22h",
      wednesday: "9h-22h",
      thursday: "9h-22h",
      friday: "9h-22h",
      saturday: "9h-22h",
      sunday: "9h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 55,
    name: "Park Padel - Embarcadero",
    address: "Embarcadero Plaza",
    city: "San Francisco",
    state: "CA",
    zipCode: "94111",
    phone: "+16506364104",
    website: "https://parkpadel.com",
    rating: 5.0,
    reviewCount: 20,
    numberOfCourts: 3,
    courtType: "outdoor" as const,
    amenities: ["Stunning Bay Views", "Community Hours", "Ferry Building Location"],
    openingHours: {
      monday: "9h-21h",
      tuesday: "9h-21h",
      wednesday: "9h-21h",
      thursday: "9h-21h",
      friday: "9h-21h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 56,
    name: "Park Padel - Oyster Point",
    address: "550-4 Eccles Ave",
    city: "South San Francisco",
    state: "CA",
    zipCode: "94080",
    phone: "+16506364104",
    website: "https://parkpadel.com",
    rating: 5.0,
    reviewCount: 18,
    numberOfCourts: 6,
    courtType: "indoor" as const,
    amenities: ["28-foot Ceilings", "Brand New Facility"],
    openingHours: {
      monday: "12:30-21h",
      tuesday: "9h-21h",
      wednesday: "9h-21h",
      thursday: "9h-21h",
      friday: "9h-21h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 57,
    name: "Park Padel - West Sacramento",
    address: "985 Riverfront St",
    city: "West Sacramento",
    state: "CA",
    zipCode: "95691",
    phone: "+12792381234",
    website: "https://parkpadel.com",
    rating: 5.0,
    reviewCount: 12,
    numberOfCourts: 4,
    courtType: "outdoor" as const,
    amenities: ["Sacramento River Views", "Waterfront Location"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 58,
    name: "Padel& Greenpoint",
    address: "73 West St",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11222",
    phone: "+19292555471",
    website: "https://www.padeland.us",
    rating: 5.0,
    reviewCount: 25,
    numberOfCourts: 6,
    courtType: "indoor" as const,
    amenities: ["Pro Shop", "Locker Rooms", "Membership Program", "Singles and Doubles Courts"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 59,
    name: "Reserve Padel - Design District",
    address: "75 NE 39th St",
    city: "Miami",
    state: "FL",
    zipCode: "33137",
    phone: "+17862249962",
    website: "https://reservepadel.com",
    rating: 5.0,
    reviewCount: 40,
    courtType: "both" as const,
    amenities: ["Pro Shop", "Lessons", "Locker Rooms", "Luxury Club", "Chief Padel Officer: Juan Martín Diaz"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 60,
    name: "Reserve Padel - Seaplane Base",
    address: "1000 MacArthur Cswy",
    city: "Miami",
    state: "FL",
    zipCode: "33132",
    phone: "+17862790722",
    website: "https://reservepadel.com",
    rating: 4.2,
    reviewCount: 30,
    courtType: "both" as const,
    amenities: ["Restaurant", "Cafe", "Events", "Kids Classes", "Waterfront Location"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 61,
    name: "Reserve Padel - Solé Mia",
    address: "2251 NE 146th St",
    city: "North Miami",
    state: "FL",
    zipCode: "33181",
    phone: "+17865626189",
    website: "https://reservepadel.com",
    rating: 5.0,
    reviewCount: 22,
    courtType: "both" as const,
    amenities: ["Private Club", "Cold Plunge", "Sauna", "Wellness Center"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 62,
    name: "Pepper Padel Miami",
    address: "1255 NW 135th St",
    city: "North Miami",
    state: "FL",
    zipCode: "33168",
    phone: "+17868368459",
    rating: 5.0,
    reviewCount: 8,
    courtType: "outdoor" as const,
    amenities: ["Coaching", "Lessons", "Public Access"],
    openingHours: {
      monday: "8h-23:30",
      tuesday: "8h-23:30",
      wednesday: "8h-23:30",
      thursday: "8h-23:30",
      friday: "8h-23:30",
      saturday: "8h-23:30",
      sunday: "8h-18h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 63,
    name: "Miami Padel Federation",
    address: "8440 NW 64th St",
    city: "Miami",
    state: "FL",
    zipCode: "33166",
    phone: "+15615197832",
    rating: 4.6,
    reviewCount: 12,
    courtType: "indoor" as const,
    amenities: ["24/7 Access", "Automated Booking"],
    openingHours: {
      monday: "24h",
      tuesday: "24h",
      wednesday: "24h",
      thursday: "24h",
      friday: "24h",
      saturday: "24h",
      sunday: "24h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 64,
    name: "Padel Up - Sterling",
    address: "Sterling",
    city: "Sterling",
    state: "VA",
    zipCode: "20166",
    website: "https://www.padelup.club",
    rating: 5.0,
    reviewCount: 15,
    numberOfCourts: 4,
    courtType: "indoor" as const,
    amenities: ["First Padel in DMV Area", "Coaching", "Lessons"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 65,
    name: "Padel Up - Culver City",
    address: "3007 Hauser Blvd",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90016",
    phone: "+18005190304",
    website: "https://www.padelup.club",
    rating: 4.1,
    reviewCount: 28,
    courtType: "indoor" as const,
    amenities: ["Gym", "Sauna", "Coaching", "Lessons"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 66,
    name: "Zmash Padel",
    address: "6635 Sterling Dr. S",
    city: "Sterling Heights",
    state: "MI",
    zipCode: "48312",
    phone: "+19472316515",
    website: "https://www.zmashpadel.com",
    rating: 5.0,
    reviewCount: 10,
    courtType: "indoor" as const,
    amenities: ["Coaching", "Lessons", "Family-Friendly"],
    openingHours: {
      monday: "9h-21h",
      tuesday: "9h-21h",
      wednesday: "9h-21h",
      thursday: "9h-21h",
      friday: "9h-21h",
      saturday: "9h-18h",
      sunday: "9h-18h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 67,
    name: "The Padel Courts",
    address: "5115 West Sunset Boulevard",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90027",
    phone: "+15107706138",
    website: "https://thepadelcourts.com",
    rating: 5.0,
    reviewCount: 22,
    numberOfCourts: 3,
    courtType: "outdoor" as const,
    amenities: ["Equipment Rental", "Coaching", "Family-Friendly", "Work & Relax Space"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 68,
    name: "P1 Padel Las Vegas",
    address: "Las Vegas",
    city: "Las Vegas",
    state: "NV",
    zipCode: "89101",
    website: "https://p1padel.com",
    rating: 5.0,
    reviewCount: 18,
    numberOfCourts: 8,
    courtType: "indoor" as const,
    amenities: ["Luxury Locker Rooms", "Pro Shop", "Members Lounge", "48 Free Parking Spaces"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 69,
    name: "Padel AZ",
    address: "555 E 18th St",
    city: "Tucson",
    state: "AZ",
    zipCode: "85701",
    phone: "+15202357094",
    website: "https://www.padelaz.com",
    rating: 5.0,
    reviewCount: 14,
    numberOfCourts: 2,
    courtType: "indoor" as const,
    amenities: ["Iron Johns Brewery On-Site", "Ball Slinger", "Free Intro Clinic"],
    openingHours: {
      monday: "varies",
      tuesday: "varies",
      wednesday: "varies",
      thursday: "varies",
      friday: "varies",
      saturday: "varies",
      sunday: "varies"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 70,
    name: "The Pad Tucson",
    address: "300 S Toole Ave",
    city: "Tucson",
    state: "AZ",
    zipCode: "85701",
    phone: "+15203722570",
    website: "https://www.thepadtucson.com",
    rating: 5.0,
    reviewCount: 28,
    numberOfCourts: 7,
    courtType: "indoor" as const,
    amenities: ["The Pad Cafe", "The Pad Bar", "Fitness Gym", "Showers", "Lockers"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-22h",
      sunday: "7h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 71,
    name: "Padel in Orlando",
    address: "8101 World Center Dr",
    city: "Orlando",
    state: "FL",
    zipCode: "32821",
    phone: "+14079905854",
    website: "https://padelorlando.com",
    rating: 4.6,
    reviewCount: 16,
    courtType: "outdoor" as const,
    amenities: ["Free Paddles", "Resort Location", "Basketball Half-Court", "USA Team Coach"],
    openingHours: {
      monday: "8h-22h",
      tuesday: "8h-22h",
      wednesday: "8h-22h",
      thursday: "8h-22h",
      friday: "8h-22h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 72,
    name: "Sodo Padel",
    address: "3180 Southgate Commerce Blvd",
    city: "Orlando",
    state: "FL",
    zipCode: "32806",
    phone: "+14079709428",
    website: "https://www.sodopadel.com",
    rating: 4.0,
    reviewCount: 8,
    courtType: "outdoor" as const,
    amenities: ["Artificial Grass", "Private Setting"],
    openingHours: {
      monday: "7:30-24h",
      tuesday: "7:30-24h",
      wednesday: "7:30-24h",
      thursday: "7:30-24h",
      friday: "7:30-24h",
      saturday: "7:30-24h",
      sunday: "7:30-24h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 73,
    name: "Sensa Padel Nashville",
    address: "1320 Adams St",
    city: "Nashville",
    state: "TN",
    zipCode: "37208",
    phone: "+19892059443",
    website: "https://sensapadel.com",
    rating: 4.2,
    reviewCount: 18,
    numberOfCourts: 6,
    courtType: "outdoor" as const,
    amenities: ["Cold Plunge", "Pilates", "Yoga", "Food & Drinks", "Live Music"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 74,
    name: "Rad Padel",
    address: "39405 Murrieta Hot Springs Rd",
    city: "Murrieta",
    state: "CA",
    zipCode: "92563",
    phone: "+13234407863",
    website: "https://radpadelsocal.com",
    rating: 5.0,
    reviewCount: 12,
    courtType: "outdoor" as const,
    amenities: ["80's Themed", "Family-Friendly", "Coaching", "Membership"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "7h-22h",
      sunday: "7h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 75,
    name: "Taktika Padel - San Diego",
    address: "4490 W Point Loma Blvd",
    city: "San Diego",
    state: "CA",
    zipCode: "92107",
    website: "https://taktikapadel.es",
    rating: 4.8,
    reviewCount: 25,
    courtType: "outdoor" as const,
    amenities: ["Paquito Navarro Academy", "Barnes Tennis Center", "Pro Padel League Host"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 76,
    name: "Padel Boston",
    address: "220 Rustcraft Rd",
    city: "Dedham",
    state: "MA",
    zipCode: "02026",
    website: "https://www.playpadelboston.com",
    rating: 5.0,
    reviewCount: 15,
    numberOfCourts: 3,
    courtType: "indoor" as const,
    amenities: ["Lounge Viewing Area", "Food & Beverage", "Events Hosting", "Mobile App"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 77,
    name: "Regency Padel Miami",
    address: "1000 NW 42nd Ave",
    city: "Miami",
    state: "FL",
    zipCode: "33126",
    rating: 4.7,
    reviewCount: 10,
    courtType: "both" as const,
    amenities: ["Glass-Enclosed Court", "Hotel Location", "Luxury Concept"],
    openingHours: {
      monday: "6h-22:30",
      tuesday: "6h-22:30",
      wednesday: "6h-22:30",
      thursday: "6h-22:30",
      friday: "6h-22:30",
      saturday: "6h-22:30",
      sunday: "6h-22:30"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 78,
    name: "Padel Life & Soccer",
    address: "1000 W Pembroke Rd",
    city: "Hallandale Beach",
    state: "FL",
    zipCode: "33009",
    phone: "+17542103913",
    rating: 4.5,
    reviewCount: 91,
    courtType: "indoor" as const,
    amenities: ["Soccer Court", "Fitness Area", "Locker Rooms", "Sports Coffee Shop", "Free Clinics"],
    openingHours: {
      monday: "9h-24h",
      tuesday: "9h-24h",
      wednesday: "9h-24h",
      thursday: "9h-24h",
      friday: "9h-24h",
      saturday: "9h-24h",
      sunday: "9h-24h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 79,
    name: "Rock Creek Tennis Center",
    address: "Near Silver Spring",
    city: "Silver Spring",
    state: "MD",
    zipCode: "20901",
    website: "https://rockcreektennis.com",
    rating: 4.3,
    reviewCount: 5,
    numberOfCourts: 1,
    courtType: "outdoor" as const,
    amenities: ["Multi-Sport Facility", "25 Tennis Courts"],
    openingHours: {
      monday: "9h-21h",
      tuesday: "9h-21h",
      wednesday: "9h-21h",
      thursday: "9h-21h",
      friday: "9h-21h",
      saturday: "9h-21h",
      sunday: "9h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 80,
    name: "Padel Social Bethesda",
    address: "5452 Westbard Avenue",
    city: "Bethesda",
    state: "MD",
    zipCode: "20816",
    phone: "+13015266339",
    website: "https://padelsocial.com",
    rating: 4.8,
    reviewCount: 12,
    numberOfCourts: 3,
    courtType: "outdoor" as const,
    amenities: ["Pro Shop", "WhatsApp Community", "First in Montgomery County"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 81,
    name: "Glassbox Padel Club",
    address: "4928 College Ave",
    city: "College Park",
    state: "MD",
    zipCode: "20740",
    website: "http://glassboxpadel.com",
    rating: 4.6,
    reviewCount: 8,
    numberOfCourts: 4,
    courtType: "outdoor" as const,
    amenities: ["Near Metro", "Founding Member Discounts"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 82,
    name: "Nicol NJ",
    address: "850 Oceanport Avenue",
    city: "Oceanport",
    state: "NJ",
    zipCode: "07757",
    phone: "+12014970177",
    website: "https://www.playatnicol.com",
    rating: 5.0,
    reviewCount: 8,
    courtType: "indoor" as const,
    amenities: ["Squash Courts", "Pickleball Courts", "Cafe", "Physical Therapy On-Site"],
    openingHours: {
      monday: "6h-22h",
      tuesday: "6h-22h",
      wednesday: "6h-22h",
      thursday: "6h-22h",
      friday: "6h-22h",
      saturday: "6h-20h",
      sunday: "6h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 83,
    name: "Golden Point Padel",
    address: "2781 Shell Rd",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11223",
    phone: "+13474698890",
    website: "https://book.goldenpointnyc.com",
    rating: 4.7,
    reviewCount: 6,
    courtType: "indoor" as const,
    amenities: ["Private Membership Club", "Elevated Experience"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 84,
    name: "Padel Haus Williamsburg",
    address: "257 Water Street",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11201",
    phone: "+19179700036",
    website: "https://www.padel.haus",
    rating: 4.5,
    reviewCount: 128,
    numberOfCourts: 4,
    courtType: "indoor" as const,
    amenities: ["Social Lounges", "Premium Fitness Equipment", "Spa-Like Locker Rooms", "Cafe & Juice Bar"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 85,
    name: "Mink Padel",
    address: "439 W 127th Street",
    city: "New York",
    state: "NY",
    zipCode: "10027",
    website: "https://mink.playbypoint.com",
    rating: 4.4,
    reviewCount: 10,
    numberOfCourts: 2,
    courtType: "outdoor" as const,
    amenities: ["First Public Manhattan Courts", "Multi-Sport Complex"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 86,
    name: "Paddles Up - East Setauket",
    address: "5 South Jersey Avenue",
    city: "Setauket",
    state: "NY",
    zipCode: "11733",
    phone: "+16316750482",
    website: "https://paddlesupny.com",
    rating: 4.8,
    reviewCount: 15,
    numberOfCourts: 3,
    courtType: "indoor" as const,
    amenities: ["Fitness Studio", "Locker Rooms", "Showers", "Saunas", "First Public Padel on Long Island"],
    openingHours: {
      monday: "9h-22h",
      tuesday: "9h-22h",
      wednesday: "9h-22h",
      thursday: "9h-22h",
      friday: "9h-22h",
      saturday: "8h-20h",
      sunday: "8h-18h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 87,
    name: "The Sports Haus",
    address: "129 Woodward Avenue",
    city: "Norwalk",
    state: "CT",
    zipCode: "06854",
    website: "https://sports.haus",
    rating: 4.9,
    reviewCount: 12,
    numberOfCourts: 5,
    courtType: "indoor" as const,
    amenities: ["Golf Simulators", "Pickleball Courts", "Modern Design", "USPA Premier Club"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 88,
    name: "Matt's Pickle and Padel",
    address: "301 Deer Run Rd",
    city: "Sewickley",
    state: "PA",
    zipCode: "15143",
    phone: "+14125344979",
    website: "https://www.mattspickleandpadel.com",
    rating: 5.0,
    reviewCount: 18,
    numberOfCourts: 4,
    courtType: "indoor" as const,
    amenities: ["Pittsburgh's ONLY Padel Facility", "Lounge Areas", "Pro Shop", "Loud Music"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 89,
    name: "Alma Padel",
    address: "2300 Ridge Dr",
    city: "Glenview",
    state: "IL",
    zipCode: "60025",
    website: "https://www.almapadel.com",
    rating: 4.9,
    reviewCount: 20,
    numberOfCourts: 5,
    courtType: "indoor" as const,
    amenities: ["Golf Simulator", "Saunas", "Lounge Areas", "Bars", "Cafe", "Mediterranean Design"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 90,
    name: "Cube Padel Chicago",
    address: "3900 South Ashland Avenue",
    city: "Chicago",
    state: "IL",
    zipCode: "60609",
    phone: "+16188364767",
    website: "https://cubepadel.com",
    rating: 5.0,
    reviewCount: 3,
    numberOfCourts: 3,
    courtType: "indoor" as const,
    amenities: ["Climate-Controlled", "Pro Shop", "Locker Rooms", "Private Parking", "Snack Bar"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "9h-20:30",
      sunday: "9h-20:30"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 91,
    name: "Padel Clube",
    address: "939 Tower Road",
    city: "Mundelein",
    state: "IL",
    zipCode: "60060",
    phone: "+12248644109",
    website: "https://www.padelclube.com",
    rating: 4.8,
    reviewCount: 12,
    courtType: "indoor" as const,
    amenities: ["Padel Gear Shop", "Personal Training", "Recovery Services", "Fall League"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 92,
    name: "Bay Padel - Treasure Island",
    address: "29 Avenue G",
    city: "San Francisco",
    state: "CA",
    zipCode: "94130",
    phone: "+14157258871",
    website: "https://baypadel.us",
    rating: 5.0,
    reviewCount: 25,
    courtType: "indoor" as const,
    amenities: ["Highest Ceilings in the World", "Breathtaking Bay Views", "Free Parking"],
    openingHours: {
      monday: "9:30-23h",
      tuesday: "9:30-23h",
      wednesday: "9:30-23h",
      thursday: "9:30-23h",
      friday: "9:30-23h",
      saturday: "9h-22h",
      sunday: "9h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 93,
    name: "Bay Padel - Dogpatch",
    address: "1070 Maryland St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94107",
    phone: "+16285028969",
    website: "https://baypadel.us",
    rating: 4.9,
    reviewCount: 18,
    numberOfCourts: 2,
    courtType: "indoor" as const,
    amenities: ["Changing Rooms", "Showers", "Lockers", "Pro Shop"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 94,
    name: "Bay Padel - Sunnyvale",
    address: "1365 Geneva Drive",
    city: "Sunnyvale",
    state: "CA",
    zipCode: "94089",
    phone: "+14084809851",
    website: "https://baypadel.us",
    rating: 5.0,
    reviewCount: 12,
    numberOfCourts: 4,
    courtType: "indoor" as const,
    amenities: ["Free Parking", "Dressing Rooms", "Gear Boutique"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 95,
    name: "Pura Padel LA",
    address: "14006 Riverside Dr",
    city: "Sherman Oaks",
    state: "CA",
    zipCode: "91423",
    phone: "+17868097175",
    website: "https://purapadel.playbypoint.com",
    rating: 5.0,
    reviewCount: 9,
    courtType: "outdoor" as const,
    amenities: ["Rooftop Courts", "Lounge Spaces", "Great Vibe"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 96,
    name: "Golden Padel",
    address: "37521 Mojave Sage Street",
    city: "Palm Desert",
    state: "CA",
    zipCode: "92211",
    website: "https://www.golden-padel.com",
    rating: 4.6,
    reviewCount: 8,
    numberOfCourts: 3,
    courtType: "outdoor" as const,
    amenities: ["First Public Padel in Coachella Valley", "Golden Hour Sessions"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 97,
    name: "Padel California",
    address: "222 South Coast Highway",
    city: "Oceanside",
    state: "CA",
    zipCode: "92054",
    phone: "+17608258365",
    website: "https://padelcalifornia.us",
    rating: 4.3,
    reviewCount: 11,
    numberOfCourts: 2,
    courtType: "outdoor" as const,
    amenities: ["Near Beach", "Women's Clinics", "Kids Lessons", "Pro Shop"],
    openingHours: {
      monday: "7:30-22h",
      tuesday: "7:30-22h",
      wednesday: "7:30-22h",
      thursday: "7:30-22h",
      friday: "7:30-22h",
      saturday: "7:30-22h",
      sunday: "7:30-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 98,
    name: "Padel N9NE",
    address: "9955 Barnes Canyon Road",
    city: "San Diego",
    state: "CA",
    zipCode: "92121",
    website: "https://www.padeln9ne.com",
    rating: 4.9,
    reviewCount: 20,
    numberOfCourts: 8,
    courtType: "indoor" as const,
    amenities: ["100,000 sq ft Facility", "Luxury Gym", "Executive Locker Rooms", "Cafe", "Wellness Center"],
    openingHours: {
      monday: "6h-23h",
      tuesday: "6h-23h",
      wednesday: "6h-23h",
      thursday: "6h-23h",
      friday: "6h-23h",
      saturday: "7h-22h",
      sunday: "7h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 99,
    name: "Kingdom of Padel",
    address: "4645 Morena Blvd",
    city: "San Diego",
    state: "CA",
    zipCode: "92117",
    website: "https://kingdomofpadel.com",
    rating: 4.7,
    reviewCount: 15,
    numberOfCourts: 4,
    courtType: "both" as const,
    amenities: ["Bar", "Cafe", "Pro Shop", "Pet-Friendly", "Golf Simulators"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 100,
    name: "Tucson Racquet & Fitness Club",
    address: "4001 N Country Club Rd",
    city: "Tucson",
    state: "AZ",
    zipCode: "85716",
    phone: "+15207956960",
    website: "https://tucsonracquetclub.com",
    rating: 4.5,
    reviewCount: 22,
    numberOfCourts: 2,
    courtType: "outdoor" as const,
    amenities: ["Full Restaurant", "Bar & Grill", "Fitness Center", "Swimming Pool", "24/7 Access"],
    openingHours: {
      monday: "24h",
      tuesday: "24h",
      wednesday: "24h",
      thursday: "24h",
      friday: "24h",
      saturday: "24h",
      sunday: "24h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 101,
    name: "SLC Padel Club",
    address: "2269 S 1200 W, Suite 105",
    city: "Woods Cross",
    state: "UT",
    zipCode: "84087",
    website: "https://www.slcpadelclub.com",
    rating: 5.0,
    reviewCount: 18,
    numberOfCourts: 3,
    courtType: "indoor" as const,
    amenities: ["Utah's First Padel Club", "Pro Store", "Padel Prep Zone", "WhatsApp Community"],
    openingHours: {
      monday: "8h-22h",
      tuesday: "8h-22h",
      wednesday: "8h-22h",
      thursday: "8h-22h",
      friday: "8h-22h",
      saturday: "8h-22h",
      sunday: "8h-19h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 102,
    name: "Racket Social Club - Denver",
    address: "82 Inverness Drive East, Suite A2",
    city: "Englewood",
    state: "CO",
    zipCode: "80112",
    phone: "+17204413410",
    website: "https://www.racketsocialclub.us",
    rating: 4.8,
    reviewCount: 16,
    courtType: "indoor" as const,
    amenities: ["Multi-Sport Facility", "Social Hub", "Events"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 103,
    name: "Denver Racquets Club",
    address: "Denver",
    city: "Denver",
    state: "CO",
    zipCode: "80202",
    rating: 4.4,
    reviewCount: 8,
    courtType: "indoor" as const,
    amenities: ["Multi-Sport Facility"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 104,
    name: "Padel 9",
    address: "Colorado Springs",
    city: "Colorado Springs",
    state: "CO",
    zipCode: "80903",
    rating: 4.6,
    reviewCount: 6,
    courtType: "outdoor" as const,
    amenities: ["Public Access"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 105,
    name: "Padel Ranch",
    address: "Colorado",
    city: "Colorado",
    state: "CO",
    zipCode: "80016",
    rating: 4.5,
    reviewCount: 4,
    courtType: "outdoor" as const,
    amenities: ["Ranch Setting"],
    openingHours: {
      monday: "8h-21h",
      tuesday: "8h-21h",
      wednesday: "8h-21h",
      thursday: "8h-21h",
      friday: "8h-21h",
      saturday: "9h-20h",
      sunday: "9h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 106,
    name: "Padel Club El Paso",
    address: "El Paso",
    city: "El Paso",
    state: "TX",
    zipCode: "79902",
    rating: 4.7,
    reviewCount: 12,
    courtType: "outdoor" as const,
    amenities: ["Community Focused"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 107,
    name: "Padel 956",
    address: "McAllen",
    city: "McAllen",
    state: "TX",
    zipCode: "78501",
    rating: 4.8,
    reviewCount: 10,
    courtType: "outdoor" as const,
    amenities: ["Border Region"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 108,
    name: "RGV Padel Club",
    address: "Brownsville",
    city: "Brownsville",
    state: "TX",
    zipCode: "78520",
    rating: 4.6,
    reviewCount: 8,
    courtType: "outdoor" as const,
    amenities: ["Rio Grande Valley"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 109,
    name: "Padel Quattro",
    address: "Albuquerque",
    city: "Albuquerque",
    state: "NM",
    zipCode: "87102",
    rating: 4.5,
    reviewCount: 6,
    courtType: "outdoor" as const,
    amenities: ["Community Courts"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 110,
    name: "Trosky Sports Club",
    address: "Albuquerque",
    city: "Albuquerque",
    state: "NM",
    zipCode: "87110",
    rating: 4.4,
    reviewCount: 5,
    courtType: "indoor" as const,
    amenities: ["Multi-Sport"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 111,
    name: "U-Padel Club - San Antonio",
    address: "San Antonio",
    city: "San Antonio",
    state: "TX",
    zipCode: "78201",
    rating: 4.9,
    reviewCount: 15,
    courtType: "indoor" as const,
    amenities: ["Multi-Location Chain"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 112,
    name: "The King of Padel - San Antonio",
    address: "San Antonio",
    city: "San Antonio",
    state: "TX",
    zipCode: "78205",
    rating: 4.7,
    reviewCount: 12,
    courtType: "outdoor" as const,
    amenities: ["Franchise Model"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 113,
    name: "Pick and Paddle",
    address: "Austin",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    rating: 4.6,
    reviewCount: 10,
    courtType: "outdoor" as const,
    amenities: ["Pickleball & Padel"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 114,
    name: "Padel Club Austin",
    address: "Austin",
    city: "Austin",
    state: "TX",
    zipCode: "78704",
    rating: 4.8,
    reviewCount: 18,
    courtType: "outdoor" as const,
    amenities: ["Austin's Padel Hub"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 115,
    name: "Padel 39",
    address: "Austin",
    city: "Austin",
    state: "TX",
    zipCode: "78739",
    rating: 4.9,
    reviewCount: 20,
    courtType: "both" as const,
    amenities: ["Multi-Location", "18 Courts Planned"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 116,
    name: "Dripping Springs Racquet Club",
    address: "Dripping Springs",
    city: "Dripping Springs",
    state: "TX",
    zipCode: "78620",
    rating: 4.5,
    reviewCount: 8,
    courtType: "outdoor" as const,
    amenities: ["Hill Country Location"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 117,
    name: "Dallas Padel Club",
    address: "Dallas",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    rating: 4.7,
    reviewCount: 15,
    courtType: "indoor" as const,
    amenities: ["Premium Facility"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 118,
    name: "Banner House at T Bar M",
    address: "New Braunfels",
    city: "New Braunfels",
    state: "TX",
    zipCode: "78132",
    rating: 4.4,
    reviewCount: 6,
    courtType: "outdoor" as const,
    amenities: ["Resort Location"],
    openingHours: {
      monday: "8h-21h",
      tuesday: "8h-21h",
      wednesday: "8h-21h",
      thursday: "8h-21h",
      friday: "8h-21h",
      saturday: "9h-20h",
      sunday: "9h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 119,
    name: "Racket Social Club - Alpharetta",
    address: "Alpharetta",
    city: "Alpharetta",
    state: "GA",
    zipCode: "30009",
    website: "https://www.racketsocialclub.us",
    rating: 4.8,
    reviewCount: 12,
    courtType: "indoor" as const,
    amenities: ["Multi-Sport", "Social Events"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 120,
    name: "Let's Go Pickleball & Padel",
    address: "Atlanta",
    city: "Atlanta",
    state: "GA",
    zipCode: "30303",
    rating: 4.5,
    reviewCount: 10,
    courtType: "indoor" as const,
    amenities: ["Multi-Sport Facility"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 121,
    name: "ITP Training Academy",
    address: "Atlanta",
    city: "Atlanta",
    state: "GA",
    zipCode: "30318",
    rating: 4.6,
    reviewCount: 8,
    courtType: "indoor" as const,
    amenities: ["Training Focus"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 122,
    name: "Marcos del Pilar - PADEL USA",
    address: "Atlanta",
    city: "Atlanta",
    state: "GA",
    zipCode: "30305",
    rating: 4.7,
    reviewCount: 9,
    courtType: "outdoor" as const,
    amenities: ["Professional Training"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 123,
    name: "Orlando Padel Club Indoor",
    address: "5950 Lakehurst Dr Unit 101",
    city: "Orlando",
    state: "FL",
    zipCode: "32819",
    phone: "+14077459030",
    rating: 4.8,
    reviewCount: 67,
    courtType: "indoor" as const,
    amenities: ["Climate Control", "Year-Round Play"],
    openingHours: {
      monday: "6h-23h",
      tuesday: "6h-23h",
      wednesday: "6h-23h",
      thursday: "6h-23h",
      friday: "6h-23h",
      saturday: "7h-22h",
      sunday: "7h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 124,
    name: "Padel World Play",
    address: "Orlando",
    city: "Orlando",
    state: "FL",
    zipCode: "32803",
    rating: 4.5,
    reviewCount: 10,
    courtType: "outdoor" as const,
    amenities: ["Community Events"],
    openingHours: {
      monday: "8h-22h",
      tuesday: "8h-22h",
      wednesday: "8h-22h",
      thursday: "8h-22h",
      friday: "8h-22h",
      saturday: "9h-21h",
      sunday: "9h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 125,
    name: "Epic Padel Inc",
    address: "Charlotte",
    city: "Charlotte",
    state: "NC",
    zipCode: "28202",
    rating: 4.6,
    reviewCount: 8,
    courtType: "indoor" as const,
    amenities: ["Modern Facility"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 126,
    name: "Charlotte Padel Club - Matthews",
    address: "2110 Pleasant Plains Rd",
    city: "Matthews",
    state: "NC",
    zipCode: "28105",
    website: "https://charlottepadelclub.com",
    rating: 4.8,
    reviewCount: 14,
    courtType: "indoor" as const,
    amenities: ["Tournaments", "Coaching", "Leagues", "Junior Academy"],
    openingHours: {
      monday: "varies",
      tuesday: "varies",
      wednesday: "varies",
      thursday: "varies",
      friday: "varies",
      saturday: "varies",
      sunday: "varies"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 127,
    name: "The Drop Club",
    address: "Puerto Rico",
    city: "San Juan",
    state: "PR",
    zipCode: "00901",
    rating: 4.7,
    reviewCount: 12,
    courtType: "outdoor" as const,
    amenities: ["Island Location"],
    openingHours: {
      monday: "8h-22h",
      tuesday: "8h-22h",
      wednesday: "8h-22h",
      thursday: "8h-22h",
      friday: "8h-22h",
      saturday: "9h-21h",
      sunday: "9h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 128,
    name: "Eco's Sports Park",
    address: "Puerto Rico",
    city: "Bayamon",
    state: "PR",
    zipCode: "00959",
    rating: 4.5,
    reviewCount: 8,
    courtType: "outdoor" as const,
    amenities: ["Sports Complex"],
    openingHours: {
      monday: "8h-22h",
      tuesday: "8h-22h",
      wednesday: "8h-22h",
      thursday: "8h-22h",
      friday: "8h-22h",
      saturday: "9h-21h",
      sunday: "9h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 129,
    name: "Riviera Tennis Center",
    address: "Puerto Rico",
    city: "Carolina",
    state: "PR",
    zipCode: "00979",
    rating: 4.6,
    reviewCount: 10,
    courtType: "outdoor" as const,
    amenities: ["Tennis & Padel", "PADEL PR ACADEMY"],
    openingHours: {
      monday: "8h-22h",
      tuesday: "8h-22h",
      wednesday: "8h-22h",
      thursday: "8h-22h",
      friday: "8h-22h",
      saturday: "9h-21h",
      sunday: "9h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 130,
    name: "RxPADEL",
    address: "1210 SW 35th Ave",
    city: "Boynton Beach",
    state: "FL",
    zipCode: "33426",
    phone: "+15613763871",
    website: "http://rxpadel.com",
    rating: 5.0,
    reviewCount: 8,
    courtType: "outdoor" as const,
    amenities: ["RSPA Certified Coaching", "Private and Group Lessons"],
    openingHours: {
      monday: "7h-19h",
      tuesday: "7h-19h",
      wednesday: "7h-19h",
      thursday: "7h-19h",
      friday: "7h-19h",
      saturday: "7h-19h",
      sunday: "7h-19h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 131,
    name: "Padel Point Miami",
    address: "1960 Normandy Dr",
    city: "Miami Beach",
    state: "FL",
    zipCode: "33141",
    phone: "+13059065896",
    rating: 4.9,
    reviewCount: 12,
    courtType: "outdoor" as const,
    amenities: ["First Miami Beach Padel Club", "Beachside Location"],
    openingHours: {
      monday: "8h-21:30",
      tuesday: "8h-21:30",
      wednesday: "8h-21:30",
      thursday: "8h-21:30",
      friday: "8h-21:30",
      saturday: "8h-21:30",
      sunday: "10h-21:30"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 132,
    name: "Brisas East Hampton",
    address: "174 Daniels Hole Rd",
    city: "East Hampton",
    state: "NY",
    zipCode: "11937",
    phone: "+16463057337",
    website: "https://brisas.us",
    rating: 5.0,
    reviewCount: 12,
    courtType: "outdoor" as const,
    amenities: ["Hamptons Location", "Outdoor Sauna", "Cold-Plunge", "4000 sq ft Outdoor Lounge"],
    openingHours: {
      monday: "8h-21h",
      tuesday: "8h-21h",
      wednesday: "8h-21h",
      thursday: "8h-21h",
      friday: "8h-21h",
      saturday: "8h-21h",
      sunday: "8h-21h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 133,
    name: "Platinum Padel Club",
    address: "1195 NE 125th St",
    city: "North Miami",
    state: "FL",
    zipCode: "33161",
    phone: "+13058482489",
    rating: 5.0,
    reviewCount: 6,
    courtType: "outdoor" as const,
    amenities: ["Family Friendly", "Unlimited Play Packages"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 134,
    name: "La Casa del Padel",
    address: "6800 W 91st St",
    city: "Grandview",
    state: "MO",
    zipCode: "66212",
    phone: "+19132146809",
    rating: 4.8,
    reviewCount: 10,
    courtType: "outdoor" as const,
    amenities: ["Community & Culture Focus"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "7h-22h",
      sunday: "7h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 135,
    name: "Padel Haus Atlanta",
    address: "Atlanta",
    city: "Atlanta",
    state: "GA",
    zipCode: "30308",
    website: "https://www.padel.haus",
    rating: 4.9,
    reviewCount: 18,
    courtType: "indoor" as const,
    amenities: ["Luxury Experience", "Spa-Like Locker Rooms", "Cafe & Juice Bar"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "8h-22h",
      sunday: "8h-22h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 136,
    name: "Taktika Padel - LA Galaxy",
    address: "18400 Avalon Blvd",
    city: "Carson",
    state: "CA",
    zipCode: "90746",
    website: "https://taktikapadel.es",
    rating: 4.7,
    reviewCount: 14,
    courtType: "outdoor" as const,
    amenities: ["LA Galaxy Facility", "Paquito Navarro Academy"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 137,
    name: "Taktika Padel - Stockton",
    address: "3398 N Pershing Ave",
    city: "Stockton",
    state: "CA",
    zipCode: "95204",
    website: "https://taktikapadel.es",
    rating: 4.6,
    reviewCount: 8,
    courtType: "outdoor" as const,
    amenities: ["University of the Pacific Campus"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 138,
    name: "Taktika Padel - Palm Desert",
    address: "45750 San Luis Rey Ave",
    city: "Palm Desert",
    state: "CA",
    zipCode: "92260",
    website: "https://taktikapadel.es",
    rating: 4.8,
    reviewCount: 12,
    courtType: "outdoor" as const,
    amenities: ["Desert Resort Setting", "WYN Tennis Academy"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 139,
    name: "Taktika Padel - Fairmont Grand Del Mar",
    address: "5300 Grand Del Mar Court",
    city: "San Diego",
    state: "CA",
    zipCode: "92130",
    website: "https://taktikapadel.es",
    rating: 4.9,
    reviewCount: 10,
    courtType: "outdoor" as const,
    amenities: ["Luxury Resort", "Padel + Pickleball"],
    openingHours: {
      monday: "7h-22h",
      tuesday: "7h-22h",
      wednesday: "7h-22h",
      thursday: "7h-22h",
      friday: "7h-22h",
      saturday: "8h-20h",
      sunday: "8h-20h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 140,
    name: "Camelback Padel Club",
    address: "Phoenix",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85016",
    phone: "+14806062300",
    website: "https://camelbackpadelclub.com",
    rating: 4.5,
    reviewCount: 8,
    numberOfCourts: 1,
    courtType: "outdoor" as const,
    amenities: ["Private", "Lighted Courts", "First Padel Court in Phoenix"],
    openingHours: {
      monday: "varies",
      tuesday: "varies",
      wednesday: "varies",
      thursday: "varies",
      friday: "varies",
      saturday: "varies",
      sunday: "varies"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
  {
    id: 141,
    name: "Padel Pals",
    address: "4945 South 71st Street",
    city: "Mesa",
    state: "AZ",
    zipCode: "85212",
    phone: "+14803183219",
    website: "https://padel-pals.com",
    rating: 5.0,
    reviewCount: 18,
    numberOfCourts: 7,
    courtType: "indoor" as const,
    amenities: ["Largest Indoor Padel Club in Phoenix", "Co-Working Spaces", "Player Lounge", "Kid's Zone"],
    openingHours: {
      monday: "7h-23h",
      tuesday: "7h-23h",
      wednesday: "7h-23h",
      thursday: "7h-23h",
      friday: "7h-23h",
      saturday: "7h-23h",
      sunday: "7h-23h"
    },
    verified: true,
    verificationDate: "2025-10-13"
  },
];

export default newClubs;
